/*All data used can be found at basketballreference.com*/

/*Create schema nba_mat;*/

/*CREATE TABLE coaches_career(
	coachid varchar(15) NOT NULL,
    firstname varchar(15),
    lastname varchar (15),
    sesason_win int,
    season_loss int,
    playoff_win int,
    playoff_loss int,
    PRIMARY KEY(coachid));
    
CREATE TABLE coaches_season(
	coachid varchar(15) NOT NULL,
    year int NOT NULL,
    yr_order int,
    firstname varchar(20),
	lastname varchar (20),
    sesason_win int,
    season_loss int,
    playoff_win int,
    playoff_loss int,
    team char(3),
    CONSTRAINT pk_coach_year PRIMARY KEY(coachid,year));
    
CREATE TABLE draft(
	draft_year int NOT NULL,
	draft_round int,
	selection int,
	team char(3),
	firstname varchar(20) NOT NULL,
	lastname varchar (20) NOT NULL,
	ilkid varchar(30),
	draft_from varchar(30),
	leag char(1),
    CONSTRAINT pk_first_last_year PRIMARY KEY(draft_year,firstname,lastname));
    
CREATE TABLE player_allstar(
	ilkid varchar(30) NOT NULL,
	year int NOT NULL,
    firstname varchar(20),
	lastname varchar (20),
    conference varchar(10),
    leag char(1),
    gp int, 
    minutes int,
    pts int,
    dreb int,
    oreb int,
    reb int,
    asts int,
    stl int, 
    blk int,
    turnover int,
    pf int,
    fga int,
    fgm int,
    fta int,
    ftm int,
    tpa int,
    tpm int,
    CONSTRAINT pk_ilkid_year PRIMARY KEY(ilkid,year));
    
CREATE TABLE player_playoffs(
	ilkid varchar(30) NOT NULL,
	year int NOT NULL,
    firstname varchar(20),
	lastname varchar (20),
    team varchar(10),
    leag char(1),
    gp int, 
    minutes int,
    pts int,
    dreb int,
    oreb int,
    reb int,
    asts int,
    stl int, 
    blk int,
    turnover int,
    pf int,
    fga int,
    fgm int,
    fta int,
    ftm int,
    tpa int,
    tpm int,
    CONSTRAINT pk_ilkid_year PRIMARY KEY(ilkid,year));
    
CREATE TABLE player_playoffs_career(
	ilkid varchar(30) NOT NULL,
    firstname varchar(20),
	lastname varchar (20),
    leag char(1) NOT NULL,
    gp int, 
    minutes int,
    pts int,
    dreb int,
    oreb int,
    reb int,
    asts int,
    stl int, 
    blk int,
    turnover int,
    pf int,
    fga int,
    fgm int,
    fta int,
    ftm int,
    tpa int,
    tpm int,
    CONSTRAINT pk_ilkid_leag PRIMARY KEY(ilkid,leag));
    
    CREATE TABLE player_regular_season(
	ilkid varchar(30) NOT NULL,
	year int NOT NULL,
    firstname varchar(20),
	lastname varchar (20),
    team varchar(10) NOT NULL,
    leag char(1),
    gp int, 
    minutes int,
    pts int,
    oreb int,
    dreb int,
    reb int,
    asts int,
    stl int, 
    blk int,
    turnover int,
    pf int,
    fga int,
    fgm int,
    fta int,
    ftm int,
    tpa int,
    tpm int,
    CONSTRAINT pk_ilkid_year_team PRIMARY KEY(ilkid,year,team));
    
    CREATE TABLE player_regular_season_career(
	ilkid varchar(30) NOT NULL,
    firstname varchar(20),
	lastname varchar (20),
    leag char(1) NOT NULL,
    gp int, 
    minutes int,
    pts int,
    oreb int,
    dreb int,
    reb int,
    asts int,
    stl int, 
    blk int,
    turnover int,
    pf int,
    fga int,
    fgm int,
    fta int,
    ftm int,
    tpa int,
    tpm int,
    CONSTRAINT pk_ilkid_leag PRIMARY KEY(ilkid,leag));
    
CREATE TABLE players(
	ilkid varchar(30) NOT NULL,
    firstname varchar(20),
	lastname varchar (20),    
    position char(1),
    firstseason int,
    lastseason int,
    h_feet int,
    h_inches double,
    weight int,
    college varchar(30),
    birthdate varchar(30),
    PRIMARY KEY(ilkid)); 

CREATE TABLE team_season(
	team char(3) NOT NULL,
    year int NOT NULL,
    leag char(1),
    o_fgm int,
    o_fga int,
    o_ftm int,
    o_fta int,
    o_oreb int,
    o_dreb int,
    o_reb int,
    o_asts int,
    o_pf int,
    o_stl int,
    o_to int,
    o_blk int,
    o_3pm int,
    o_3pa int,
    o_pts int,
    d_fgm int,
    d_fga int,
    d_ftm int,
    d_fta int,
    d_oreb int,
    d_dreb int,
    d_reb int,
    d_asts int,
    d_pf int,
    d_stl int,
    d_to int,
    d_blk int,
    d_3pm int,
    d_3pa int,
    d_pts int,
    pace int,
    won int,
    lost int,
    CONSTRAINT pk_team_year PRIMARY KEY(team,year));
    
CREATE TABLE teams(
	team char(3) NOT NULL,
	location varchar(20),
	name varchar(20),
	leag char(1) NOT NULL,
    CONSTRAINT pk_team_leag PRIMARY KEY(team,leag)); */